# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a42e7184f4a3032b16a090c0caa92446045147760d0edaa2e659962a459492bb9bcf4b5c724fcd01971f7b892ac8058bc85caae230be5357f7eec185eaa0604b

test:
  secret_key_base: 93e78bccbed2b83d3ab0ecb399ff4584a323ebc2f8544e29fe2d639a143d88c83ed554c3c2b6c3a1e972ed88e5cee6c72eeaad3fac11a0a51c17ae6863464c3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
